"""Ridge with training-only median imputation and scaling, saved as one bundle."""
from __future__ import annotations

import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.exceptions import ConvergenceWarning
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from threadpoolctl import threadpool_limits


def train_model(x: pd.DataFrame, y: np.ndarray, params: dict, threads: int,
                progress=None) -> dict:
    """Only the already time-split supervised training frame is fitted."""
    columns = list(x.columns)
    if len(columns) != len(set(columns)) or not np.isfinite(y).all():
        raise ValueError("Invalid Ridge feature columns or training labels.")
    values = x.to_numpy(dtype="float64", copy=True)
    if np.isinf(values).any():
        raise ValueError("Ridge features contain infinity.")
    pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median", copy=False, keep_empty_features=True)),
        ("scaler", StandardScaler(copy=False)),
        ("ridge", Ridge(**params, copy_X=False)),
    ])
    if progress:
        progress(f"Ridge fit: rows={len(y):,}, alpha={params['alpha']}, training-only preprocessing")
    with threadpool_limits(limits=threads), warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always", ConvergenceWarning)
        pipe.fit(values, y)
    warning_messages = [str(w.message) for w in caught]
    if any(issubclass(w.category, ConvergenceWarning) for w in caught):
        raise RuntimeError(f"Ridge convergence warning: {warning_messages}")
    model = pipe.named_steps["ridge"]
    iterations = np.asarray(model.n_iter_).astype(int).tolist()
    if max(iterations) >= params["max_iter"]:
        raise RuntimeError("Ridge reached its fixed iteration limit; do not select this run.")
    if not np.isfinite(model.coef_).all() or not np.isfinite(model.intercept_).all():
        raise RuntimeError("Ridge coefficients are not finite.")
    fitted_rows = int(pipe.named_steps["scaler"].n_samples_seen_)
    if fitted_rows != len(y):
        raise AssertionError("Scaler was fitted on a different training cohort.")
    info = {"params": dict(params), "n_iter": iterations, "warnings": warning_messages,
            "hit_iteration_limit": False, "preprocessing_fit_rows": fitted_rows,
            "preprocessing": "training-only median + StandardScaler; no target transform"}
    if progress:
        progress(f"Ridge fit finished: iterations={iterations}; warnings={len(warning_messages)}")
    return {"schema": 1, "columns": columns, "pipeline": pipe, "info": info,
            "threads": threads}


def predict_model(bundle: dict, x: pd.DataFrame, batch_rows: int = 100_000) -> np.ndarray:
    if list(x.columns) != bundle["columns"] or batch_rows < 1:
        raise ValueError("Ridge prediction feature order/batch size differs from the bundle.")
    result = np.empty(len(x), dtype="float64")
    with threadpool_limits(limits=bundle["threads"]):
        for start in range(0, len(x), batch_rows):
            stop = min(start + batch_rows, len(x))
            values = x.iloc[start:stop].to_numpy(dtype="float64", copy=True)
            if np.isinf(values).any():
                raise ValueError("Prediction features contain infinity.")
            result[start:stop] = bundle["pipeline"].predict(values)
    if not np.isfinite(result).all():
        raise ValueError("Ridge generated missing/infinite predictions.")
    return result


def save_model(bundle: dict, path: Path) -> None:
    # Only load bundles generated by this project, never an untrusted pickle.
    joblib.dump(bundle, path)


def load_model(path: Path) -> dict:
    bundle = joblib.load(path)
    if bundle.get("schema") != 1 or not isinstance(bundle.get("pipeline"), Pipeline):
        raise ValueError("Invalid local Ridge bundle.")
    return bundle
